<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">
  <PropertyGroup>
    <CohesionApplicationName>identity</CohesionApplicationName>
    <!-- A gateway is always enabled by Sdk.Gateway. -->
    <CohesionGateways>Local;InProcess</CohesionGateways>
    <CohesionGatewayInProcess>true</CohesionGatewayInProcess>
  </PropertyGroup>
  <ItemGroup>
    <CohesionResourceReference Include="..\Example.Identity.IdentityHub\Example.Identity.IdentityHub.csproj" />
  </ItemGroup>
</Project>
