<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">
  <PropertyGroup>
    <CohesionApplicationName>identity</CohesionApplicationName>
    <CohesionGateways>Local;InProcess;Docker;Kubernetes</CohesionGateways>
    <CohesionGatewayInProcess>true</CohesionGatewayInProcess>
  </PropertyGroup>
  <ItemGroup>
    <CohesionResourceReference Include="..\Example.Identity.IdentityHub\Example.Identity.IdentityHub.csproj" />
  </ItemGroup>
</Project>
