<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">
  <PropertyGroup>
    <CohesionApplicationName>identity</CohesionApplicationName>
    <CohesionApplicationModel>enabled</CohesionApplicationModel>
    <CohesionGateways>Local;InProcess</CohesionGateways>
    <CohesionGatewayInProcess>true</CohesionGatewayInProcess>
    <CohesionResourceReferencesAreRuntime>true</CohesionResourceReferencesAreRuntime>
  </PropertyGroup>
  <ItemGroup>
    <CohesionResourceReference Include="..\Example.Identity.IdentityHub\Example.Identity.IdentityHub.csproj" />
  </ItemGroup>
</Project>
