using Assimalign.Cohesion.ApplicationModel;
using Example.AppB.Gateway;

// The appb application. The Add* verbs and the Externals class are generated by Sdk.Gateway from the referenced
// manifests; DependsOn edges are inferred from each resource's own references, so nothing is listed twice. What this zone
// needs FROM the resources it references (an audience in Identity, a configuration namespace in Platform, a development
// DNS record in Networking) is declared as commands on those references — each area owns its entire dependency tree.
// Run standalone by `dotnet run`.
IApplicationBuilder builder = Gateway.CreateBuilder(args);   // generated: Application.CreateBuilder("appb", args); honors --environment

var secrets  = builder.AddAppBSecretStore();

// Crossings into other applications, bound in code to where they live (the peer gateways' control planes).
// Environment always overrides: --external identity-hub=https=<url>, or Cohesion:External:* in configuration;
// --realize identity-hub runs Identity locally from source instead.
var config   = builder.RemoteReference(Externals.PlatformConfigurationStore, remote => remote.Gateway("https://platform.example.com/cohesion"));
var identity = builder.RemoteReference(Externals.IdentityHub, remote => remote.Gateway("https://identity.example.com/cohesion"));

var database = builder.AddAppBDatabase();                              // DependsOn(secrets) inferred
var api      = builder.AddAppBApi(options => options.Replicas = 2);    // DependsOn(database, secrets, config, identity) inferred
var spa      = builder.AddAppBSpa().DependsOn(api);                    // explicit ordering edge (additive)

// Declarative commands: delivered to each target's default control plane (through the peer gateway's control plane when
// remote) once the target is Running; owned by appb; removed on --mode teardown. Identity and Platform list no zones.
identity.AddAudience("appb-api");
identity.AddClient("appb-spa", client => client.AuthorizationCode().RedirectUri(spa.Endpoints.Http.PublicUrl("/callback")).Audience("appb-api"));
config.AddNamespace("appb", seed: "Configuration/appb.json");
if (builder.Environment.IsDevelopment())
{
    var dns = builder.RemoteReference(Externals.NetworkingRezolvr, remote => remote.Gateway("https://networking.example.com/cohesion"));
    dns.AddARecord("appb-dev", api.Endpoints.Https);               // a development record in the org's DNS; gone when this gateway tears down
}

builder.UseGateway(args);                                    // --gateway local|inprocess|docker|kubernetes (default: COHESION_GATEWAY, then Development → local)
// Platform-specific exceptions (rare) go here and nowhere else: builder.UseGateway(args, gateways => gateways.Kubernetes(k => ...)); the callback runs only when that gateway is selected.
await builder.Build().RunAsync();                            // --mode run|apply|teardown|bootstrap|describe · --context cluster-0N · --external name=<ep>=<url> · --realize <name>
