using Assimalign.Cohesion.ApplicationModel;
using Example.AppC.Gateway;

// The appc application. The Add* verbs and the Externals class are generated by Sdk.Gateway from the referenced
// manifests; DependsOn edges are inferred from each resource's own references, so nothing is listed twice. What this zone
// needs FROM the resources it references (an audience in Identity, a configuration namespace in Platform, a development
// DNS record in Networking) is declared as commands on those references — each area owns its entire dependency tree.
// Run standalone by `dotnet run`; the root Example.Gateway application set (k8s/Gateway) obtains this same model through this gateway's control plane (`--mode describe`) and reconciles it with the other areas, resolving crossings between member applications in-process.
IApplicationBuilder builder = Gateway.CreateBuilder(args);   // generated: Application.CreateBuilder("appc", args); honors --environment

var secrets  = builder.AddAppCSecretStore();

// Crossings into other applications, bound in code to where they live (the same cluster's namespaces through the operator kubeconfig channel; the context comes from Cohesion:Kubernetes:Context).
// Environment always overrides: --external identity-hub=https=<url>, or Cohesion:External:* in configuration;
// --realize identity-hub runs Identity locally from source instead.
var config   = builder.RemoteReference(Externals.PlatformConfigurationStore, remote => remote.Kubernetes("platform"));
var identity = builder.RemoteReference(Externals.IdentityHub, remote => remote.Kubernetes("identity"));

var database = builder.AddAppCDatabase();                              // DependsOn(secrets) inferred
var api      = builder.AddAppCApi(options => options.Replicas = 2);    // DependsOn(database, secrets, config, identity) inferred
var spa      = builder.AddAppCSpa().DependsOn(api);                    // explicit ordering edge (additive)

// Declarative commands: delivered to each target's default control plane (through the peer gateway's control plane when
// remote) once the target is Running; owned by appc; removed on --mode teardown. Identity and Platform list no zones.
identity.AddAudience("appc-api");
identity.AddClient("appc-spa", client => client.AuthorizationCode().RedirectUri(spa.Endpoints.Http.PublicUrl("/callback")).Audience("appc-api"));
config.AddNamespace("appc", seed: "Configuration/appc.json");
if (builder.Environment.IsDevelopment())
{
    var dns = builder.RemoteReference(Externals.NetworkingRezolvr, remote => remote.Kubernetes("networking"));
    dns.AddARecord("appc-dev", api.Endpoints.Https);               // a development record in the org's DNS; gone when this gateway tears down
}

builder.UseGateway(args);                                    // --gateway local|inprocess|docker|kubernetes (default: COHESION_GATEWAY, then Development → local)
// Platform-specific exceptions (rare) go here and nowhere else: builder.UseGateway(args, gateways => gateways.Kubernetes(k => ...)); the callback runs only when that gateway is selected.
await builder.Build().RunAsync();                            // --mode run|apply|teardown|bootstrap|describe · --context cluster-0N · --external name=<ep>=<url> · --realize <name>
