<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">
  <PropertyGroup>
    <CohesionApplicationName>platform</CohesionApplicationName>
    <CohesionApplicationModel>enabled</CohesionApplicationModel>
    <CohesionGateways>Local;InProcess</CohesionGateways>
    <CohesionGatewayInProcess>true</CohesionGatewayInProcess>
    <CohesionResourceReferencesAreRuntime>true</CohesionResourceReferencesAreRuntime>
  </PropertyGroup>
  <ItemGroup>
    <CohesionResourceReference Include="..\Example.Platform.SecretStore\Example.Platform.SecretStore.csproj" />
    <CohesionResourceReference Include="..\Example.Platform.ConfigurationStore\Example.Platform.ConfigurationStore.csproj" />
    <CohesionResourceReference Include="..\Example.Platform.LogSpace\Example.Platform.LogSpace.csproj" />
  </ItemGroup>
</Project>
