<Project Sdk="Assimalign.Cohesion.Sdk.Gateway">
  <PropertyGroup>
    <CohesionApplicationName>networking</CohesionApplicationName>
    <!-- A gateway is always enabled by Sdk.Gateway. -->
    <CohesionGateways>Local</CohesionGateways>   <!-- no InProcess: the VPN data plane is composable=false -->
  </PropertyGroup>
  <ItemGroup>
    <CohesionResourceReference Include="..\Example.Networking.Rezolvr\Example.Networking.Rezolvr.csproj" />
    <CohesionResourceReference Include="..\Example.Networking.VpnGateway\Example.Networking.VpnGateway.csproj" />
  </ItemGroup>
</Project>
